apiVersion: v1
kind: Service
metadata:
  name: cloudtrader-traders
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: cloudtrader-traders
  ports:
  - port: 80
    targetPort: 80