apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloudtrader-traders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudtrader-traders
  template:
    metadata:
      labels:
        app: cloudtrader-traders
    spec:
      containers:
      - name:cloudtrader-traders
        image: cloudtrader.azurecr.io/cloudtrader-traders:latest
        ports:
        - containerPort: 80